### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/orb-gmbal-commons#1]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.
